### ISSUE TITLE
Update VPC infrastructure resources (Gen1 and Gen2)

### ISSUE THREAD

**Issue by hkantare** [ibm-cloud-docs/terraform#32]
https://cloud.ibm.com/docs/terraform?topic=terraform-vpc-gen2-resources#network-acl
https://cloud.ibm.com/docs/terraform?topic=terraform-vpc-gen1-resources#network-acl

Update the rules parameter description
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/website/docs/r/is_network_acl.html.markdown
---------------------------------------------------------------------------------------

https://cloud.ibm.com/docs/terraform?topic=terraform-vpc-gen1-resources#provider-floating-ip
https://cloud.ibm.com/docs/terraform?topic=terraform-vpc-gen2-resources#provider-floating-ip

Add tags parameter
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/website/docs/r/is_floating_ip.html.markdown
---------------------------------------------------------------------------------------
https://cloud.ibm.com/docs/terraform?topic=terraform-vpc-gen1-resources#provider-public-gateway
https://cloud.ibm.com/docs/terraform?topic=terraform-vpc-gen2-resources#provider-public-gateway

Add tags and resource_group parameters
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/website/docs/r/is_public_gateway.html.markdown
---------------------------------------------------------------------------------------

**Comment by Nadine2016** [comment]
documentation was updated accordingly

**Comment by Nadine2016** [comment]
reviewed by Harini. Closing
