### ISSUE TITLE
Update Kubernetes service resource-ibm_container_cluster

### ISSUE THREAD

**Issue by hkantare** [ibm-cloud-docs/terraform#33]
https://cloud.ibm.com/docs/terraform?topic=terraform-container-resources#container-cluster

Deprecatd `billing` and `is_trusted` argument 
Added `gateway_enabled` argument

https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/website/docs/r/container_cluster.html.markdown

**Comment by Nadine2016** [comment]
Updated documentation accordingly.

**Comment by Nadine2016** [comment]
reviewed by Harini. Closing
