### ISSUE TITLE
Update Identity & Access (IAM) resources ->iam-user-invite

### ISSUE THREAD

**Issue by hkantare** [ibm-cloud-docs/terraform#35]
https://cloud.ibm.com/docs/terraform?topic=terraform-iam-resources&-access-data-sources#iam-user-invite

Added a note section
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/website/docs/r/iam_user_invite.html.markdown

**Comment by Nadine2016** [comment]
note was added to the classic infrastructure roles parameter in the table.

**Comment by Nadine2016** [comment]
reviewed by Harini. Closing
