### ISSUE TITLE
Examples' syntax is not compliant with Terraform 0.12

### ISSUE THREAD

**Issue by azaceta** [ibm-cloud-docs/terraform#36]
There are several changes required to the examples provided to make them Terraform 0.12 compatible.
Interpolated names like ${..} are not used anymore, and require removing quotes at some point like for API keys.
Blocks now don't use '=' so current examples fail
There are others. A potential fix is running the config files through 
`terraform 0.12upgrade`

**Comment by Nadine2016** [comment]
@azaceta thanks for pointing that out. We are working on updating the entire doc set for this change. I'll keep you posted.

**Comment by Nadine2016** [comment]
@azaceta just wanted to give a short update that we added migration steps for Terraform v0.12 and also updated the examples for v0.12 in our staging environment. however, we are waiting to push out these changes probably until the end of the month when we officially support v0.12 in IBM Cloud Schematics. Let me know if you need any of those examples in the meantime and I will provide them to you as you obviously can't access our staging environment. I am very sorry for the inconvenience and confusion that this might cause. :-/ let me know if you have any questions. Thank you

**Comment by Nadine2016** [comment]
@azaceta @Mallear as of today, Schematics now supports Terraform version 0.12. As a result, we updated the examples in the docs for Terraform version 0.12 as well. I am closing this issue. Let me know if you have questions or if you run into other issues with the documentation. Thank you so much!
