### ISSUE TITLE
VPC gen1 and VPC gen2 resources missing ibm_is_instance and ibm_is_vpc_route

### ISSUE THREAD

**Issue by hkantare** [ibm-cloud-docs/terraform#37]
https://ibm-cloud.github.io/tf-ibm-docs/v1.2.1/

Route: https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/website/docs/r/is_vpc_route.html.markdown
Instance : https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/website/docs/r/is_instance.html.markdown

**Comment by Nadine2016** [comment]
docs were added for both instances in the following places: 
https://test.cloud.ibm.com/docs/terraform?topic=terraform-vpc-gen2-resources#provider-route
https://test.cloud.ibm.com/docs/terraform?topic=terraform-vpc-gen2-resources#provider-instance
https://test.cloud.ibm.com/docs/terraform?topic=terraform-vpc-gen1-resources#provider-route
https://test.cloud.ibm.com/docs/terraform?topic=terraform-vpc-gen1-resources#provider-instance
