### ISSUE TITLE
Terraform version shows 1.12 - should be 0.12, right?

### ISSUE THREAD

**Issue by mikehollinger** [ibm-cloud-docs/terraform#38]
https://github.com/ibm-cloud-docs/terraform/blob/master/tf-provider.md shows 1.12 for the terraform version, and it should probably be 0.12 right?

**Comment by Nadine2016** [comment]
@mikehollinger thanks for catching that. You are totally right.  I have updated the docs and the update should be in prod in a couple of minutes.
