### ISSUE TITLE
Add new provider level argument zone

### ISSUE THREAD

**Issue by hkantare** [ibm-cloud-docs/terraform#42]
* Added a new provider level argument zone . This parameter is optional and used for Power virtual resources/datasources to work in multi-zone concept
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/website/docs/index.html.markdown

https://cloud.ibm.com/docs/terraform?topic=terraform-tf-provider

**Comment by Nadine2016** [comment]
added here: https://cloud.ibm.com/docs/terraform?topic=terraform-provider-reference
closing
