### ISSUE TITLE
Add new attributes for ibm_container_vpc_cluster

### ISSUE THREAD

**Issue by hkantare** [ibm-cloud-docs/terraform#43]
https://cloud.ibm.com/docs/terraform?topic=terraform-container-resources#vpc-cluster

Added argument `wait_till` and two attributes `ingress_hostname` ingress_secret` to resource and Note section on `wait_till`

https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/website/docs/r/container_vpc_cluster.html.markdown
**************************************************************************************

https://cloud.ibm.com/docs/terraform?topic=terraform-container-data-sources#container-vpc-cluster

Added two attributes `ingress_hostname` ingress_secret` to datasource 

https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/website/docs/d/container_vpc_cluster.html.markdown

**Comment by Nadine2016** [comment]
completed. closing
