### ISSUE TITLE
Cloud Database data source object has two output with the same name

### ISSUE THREAD

**Issue by Mallear** [ibm-cloud-docs/terraform#46]
Hello,

I figured that Cloud Database data source list two output parameters with the same name `id`. I guess one of them could be renamed CRN.

**Comment by Nadine2016** [comment]
@Mallear thanks for catching that. I am looking into this and will let you know.

**Comment by Nadine2016** [comment]
@Mallear I got the confirmation that the second `id` output parameter should actually be named `crn`. I made the update in the doc and it is on its way to prod. I am closing this issue, but let me know if you have any questions.

**Comment by Mallear** [comment]
Thank you :)
