### ISSUE TITLE
Incorrect source tree structure in documentation

### ISSUE THREAD

**Issue by ibmchas** [ibm-cloud-docs/terraform#48]
Looks like you have changed the directory structure your branch without updating the documentation, in section **"Importing infrastructure information from Terraform"**

Step number 3 - Navigate into the ibm_ansible_dyn_inv directory.
 
`cd terraform-provider-ibm/examples/ansible/ibm_ansible_dyn_inv`

Should be 

`cd terraform-provider-ibm/examples/ibm-ansible-samples/ibm_ansible_dyn_inv`

**Comment by Nadine2016** [comment]
@ibmchas thanks for catching that. The file path is updated and the update is on its way to prod. closing this issue
