### ISSUE TITLE
vpn-gateway-connection preshared_key required

### ISSUE THREAD

**Issue by chanster** [ibm-cloud-docs/terraform#51]
Under the `vpn-gateway-connection` [documentation](https://cloud.ibm.com/docs/terraform?topic=terraform-vpc-gen2-resources#vpn-gateway-connection), it states `preshared_key` is optional but terraform requires it.

```
Error: Missing required argument

  on main.tf line 143, in resource "ibm_is_vpn_gateway_connection" "shared-vpn-gwc-mkt-us-south-1":
 143: resource "ibm_is_vpn_gateway_connection" "shared-vpn-gwc-mkt-us-south-1" {

The argument "preshared_key" is required, but no definition was found.
```

**Comment by Nadine2016** [comment]
@chanster so sorry for not getting back to you earlier. I just saw your issue today. Thank you so much for your feedback. I will adjust the documentation and push it out today.

**Comment by Nadine2016** [comment]
@chanster change is on its way to prod. I am closing the issue, but let me know if you find anything else. Thank you so much.
