### ISSUE TITLE
Resource key parameter wrong format

### ISSUE THREAD

**Issue by Mallear** [ibm-cloud-docs/terraform#52]
Hello,

I tried to create a database credential key using a ibm_resource_key object with parameter `service-endpoints`.

I ended with the format:

```hcl
  parameters = {
    service-endpoints = "private"
  }
```
instead of the given format (https://cloud.ibm.com/docs/terraform?topic=terraform-resource-mgmt-resources#resource-key-sample):

```hcl
  parameters = {
    "service-endpoints" = "private"
  }
```

Maybe adding an exemple to create credentials for private databases endpoint could be usefull as it's not something available through the web console.

**Comment by Nadine2016** [comment]
@Mallear Thanks for your feedback. To understand the issue better, are you saying that an existing example is wrong? Or that we are missing this particular example? I could not find an existing example that might be wrong in the docs, but from reading your text it sounds like we have one. Maybe you can point me to the right place.

**Comment by Mallear** [comment]
@Nadine2016  Sorry if I wasn't clear :) 

The existing exemple here https://cloud.ibm.com/docs/terraform?topic=terraform-resource-mgmt-resources#creating-credentials-for-a-service-id has a format issue, the parameter block should look like this:

```hcl
  parameters {
    serviceid_crn = ibm_iam_service_id.serviceID.crn
  }
```
instead of:
```hcl
  parameters {
    "serviceid_crn" = ibm_iam_service_id.serviceID.crn
  }
```
Using double quote around the parameter name make terraform fail.

**Comment by Nadine2016** [comment]
@Mallear aaaah I see. Yes, I'll definitely update that and add an example for creating service credentials that use the private service endpoint.

**Comment by Mallear** [comment]
Thank you very much @Nadine2016

**Comment by Nadine2016** [comment]
@Mallear so I added this example here https://cloud.ibm.com/docs/terraform/provider?topic=terraform-resource-mgmt-resources#resource-key-sample-private and also updated the other example. Let me know what you think.

**Comment by Mallear** [comment]
@Nadine2016 Shouldn't you use an ibm_database resource instead of ibm_resource_instance to create a database instance ?

**Comment by Nadine2016** [comment]
@Mallear hmm... interesting question. the example that I added definitely worked. I will look into the database resource.

**Comment by Mallear** [comment]
I'm using this to create an instance for databases-for-postgres/redis/elasticsearch:

```hcl
resource "ibm_database" "database" {
  name              = "db"
  plan              = "standard"
  location          = "eu-de"
  resource_group_id = data.ibm_resource_group.resource_group.id

  service = "databases-for-postgresql"
  version = 11

  service_endpoints            = "private"
  adminpassword                = "password"
  members_memory_allocation_mb = 3072
  members_disk_allocation_mb   = 61440

}
```

**Comment by Mallear** [comment]
Hello @Nadine2016,

I've noticied that the exemple for ibm_resource_instance has the same format error (https://cloud.ibm.com/docs/terraform/provider?topic=terraform-resource-mgmt-resources#resource-instance) witch parameter HMAC between quotes.

**Comment by Nadine2016** [comment]
@Mallear Thanks so much. I updated the example as well. I also got the feedback from the Terraform dev team that. we should use the `ibm_database` resource as it allows for more things to be configured. So I updated the example as well. Let me know what you think. The update should be available within a couple of minutes. Let me know what you think.

**Comment by Mallear** [comment]
@Nadine2016 Everything's good for me :) Thank you

**Comment by Nadine2016** [comment]
awesome. thank you. Closing the issue :-)
