### ISSUE TITLE
IBM terraform provider install instructions not working on linux

### ISSUE THREAD

**Issue by mriedem** [ibm-cloud-docs/terraform#55]
I'm trying to follow the instructions here to get the IBM cloud provider for terraform working:

https://cloud.ibm.com/docs/terraform?topic=terraform-setup_cli#install_cli

This is my OS:

```
$ uname -a
Linux osboxes 5.3.0-26-generic #28~18.04.1-Ubuntu SMP Wed Dec 18 16:40:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

I have terraform v0.12.20 installed:

```
$ terraform version
Terraform v0.12.20
```

I have downloaded the v1.4.0 zip from here:

https://github.com/IBM-Cloud/terraform-provider-ibm/releases/download/v1.4.0/linux_amd64.zip

**NOTE:** The instructions in the docs don't mention extracting this to get the binary, that should probably be updated.

I follow the steps to put the extracted binary in `$HOME/.terraform.d/plugins` and I can run the binary:

```
$ ~/.terraform.d/plugins/terraform-provider-ibm_v1.4.0 
2020/04/20 21:34:10 IBM Cloud Provider version 1.4.0  
This binary is a plugin. These are not meant to be executed directly.
Please execute the program that consumes these plugins, which will
load any plugins automatically
```

But when I try to run `terraform init` from my project I get this:

```$ terraform init
Initializing modules...
<snip>

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...

Provider "ibm" not available for installation.

A provider named "ibm" could not be found in the Terraform Registry.

This may result from mistyping the provider name, or the given provider may
be a third-party provider that cannot be installed automatically.

In the latter case, the plugin must be installed manually by locating and
downloading a suitable distribution package and placing the plugin's executable
file in the following directory:
    terraform.d/plugins/linux_amd64

Terraform detects necessary plugins by inspecting the configuration and state.
To view the provider versions requested by each module, run
"terraform providers".


Error: no provider exists with the given name
```

Note that the error message says the plugin should be in `terraform.d/plugins/linux_amd64`. I'm not sure if that is a typo and it should say `~/.terraform.d/plugins/linux_amd64` or not. Regardless, I try copying the binary there, verify it works:

```
$ ~/.terraform.d/plugins/linux_amd64/terraform-provider-ibm_v1.4.0 
2020/04/20 21:41:18 IBM Cloud Provider version 1.4.0  
This binary is a plugin. These are not meant to be executed directly.
Please execute the program that consumes these plugins, which will
load any plugins automatically
```

But terraform still doesn't recognize the provider and I get the same error as above.

Any ideas of what might be wrong?

**Comment by mriedem** [comment]
I figured out my problem. I'm trying to use an _existing_ terraform project which requires the ibm terraform provider at version 1.2.6 exactly but I had version 1.4.0. The error message from `terraform init` is not at all clear that it's a version mismatch issue since it says it can't find the provider.

I didn't realize the problem until I ran `terraform plan` and got this:

```
Error: provider.ibm: no suitable version installed
  version requirements: "= 1.2.6"
  versions installed: "1.4.0"
```

Once I changed the required version of the provider to `>= 1.2.6` as a test did it work:

```
$ terraform init
Initializing modules...

Initializing the backend...

Initializing provider plugins...

Terraform has been successfully initialized!
```

I'm not sure if there is anything to do with _this_ issue now since I figured out the problem and it wasn't really with the IBM provider install instructions (except for that noted difference in install docs about extracting the zip to get the binary). The bigger issue is the misleading error from `terraform init` but I'm assuming that's a bug in terraform core rather than the ibm provider plugin. Feel free to close this is there is nothing to do from the IBM cloud docs perspective.

**Comment by Nadine2016** [comment]
@mriedem thanks so much for your feedback. I am updating the documentation to include the extraction step. Regarding the `terraform init` message, I checked with our development team and as you already assumed, it is coming from Terraform, not the IBM provider. So nothing really that we can do on our side to improve this unfortunately. I am very happy that you were able to figure out what the issue was and that everything worked for you. Let me know if you run into any other issue.  We are happy to help and look into it. :-) I am closing this issue but you can expect the update to be available in the documentation within the next hour or two.
