### ISSUE TITLE
Missing ansible folder

### ISSUE THREAD

**Issue by fabionzn** [ibm-cloud-docs/terraform#58]
So I am following the tutorial, but might found an issue on the second step in https://cloud.ibm.com/docs/terraform?topic=terraform-deploy_wordpress&locale=en#setup_ansible_single_site_wordpress.
When I tried to copy/move the folder **terraform-provider-ibm/examples/ansible/ibm_ansible_wordpress/*** it shows that there is no such folder, searching in the git project I was able to find on other path **terraform-provider-ibm/examples/ibm-ansible-samples/ibm_ansible_wordpress**

**Comment by Nadine2016** [comment]
@fabionzn thank you so much for catching that. we have updated the docs accordingly and this change will go out with our next prod push. closing this issue.
