### ISSUE TITLE
cannot find link to get classic infra userid+passwd

### ISSUE THREAD

**Issue by osmanburucu-ibm** [ibm-cloud-docs/terraform#59]
the given link does not work: 
---
Retrieve your IBM Cloud classic infrastructure user name and API key. You use this user name and API key to provision the classic infrastructure virtual server in your IBM Cloud account.
---
https://cloud.ibm.com/docs/iam?topic=iam-classic_keys

**Comment by Nadine2016** [comment]
@osmanburucu-ibm we are sorry that you had to run into this. the link just recently changed to https://cloud.ibm.com/docs/account?topic=account-classic_keys the doc is already updated and the change will be available in prod with our next prod push.
