### ISSUE TITLE
ibm_is_lb_listener causes web console error when default_pool is undefined

### ISSUE THREAD

**Issue by chanster** [ibm-cloud-docs/terraform#61]
If `default_pool` is not defined in the terraform config, it will deploy the listener with an undefined default pool.

The web console can errors when viewing this load balancer with this configuration.

**Terraform config:**
```terraform
resource "ibm_is_lb_listener" "my_listener" {
  lb       = ibm_is_lb.my_lb.id
  port     = "80"
  protocol = "http"
}
```

**Web Console Error:**
```
Path: loadBalancer
Details: Expected a value of type "Identifier" but received: { 0: "u", 1: "n", 2: "d", 3: "e", 4: "f", 5: "i", 6: "n", 7: "e", 8: "d", resourceID: undefined, region: "us-south" }
Reference ID: 1596466567838
--------------------------------------
""
```
**Work Around:**
Add `default_pool`
```terraform
resource "ibm_is_lb_listener" "my_listener" {
  lb       = ibm_is_lb.my_lb.id
  port     = "80"
  protocol = "http"
  default_pool = ibm_is_lb_pool.my_pool.id
}
```

**Question:**
Is the `default_pool` actually `required` and not `optional`?

**Comment by geethasm** [comment]
We are working on this.

**Comment by geemurth** [comment]
This is [updated](https://cloud.ibm.com/docs/terraform?topic=terraform-vpc-gen1-resources#lb-listener) and we are closing. Thanks for catching this.
