### ISSUE TITLE
IBM_CLOUD API

### ISSUE THREAD

**Issue by Dharuman007** [ibm-cloud-docs/terraform#63]
how to get ibm resources list for migration using ibm API

**Comment by geemurth** [comment]
Hi Dharum, 
Could you please elaborate about the migration using IBM CLoud API or API key?
Thanks,
Geetha

**Comment by Dharuman007** [comment]
IBM Cloud API

**Comment by geemurth** [comment]
Hi Dharum, Could you please check these links meets your requirement: []([https://cloud.ibm.com/docs/terraform?topic=terraform-manage_resources](url)
FAQ: [https://cloud.ibm.com/docs/account?topic=account-resources-faq](url)  and  For all the resources to be provisioned in IBM Cloud, refer Controller API [https://cloud.ibm.com/apidocs/resource-controller/resource-controller#list-resource-instances](url)
Regards,
Geetha
,

**Comment by geemurth** [comment]
Hi Dharum,
Could you please close the issue, if the provided information meets your requirement. 
Thanks, Geetha
