### ISSUE TITLE
Update tutorials to reflect changes in terraform-provider-ibm repo

### ISSUE THREAD

**Issue by rampadc** [ibm-cloud-docs/terraform#65]
Please go through your tutorials and update instructions and links.

The master branch to https://github.com/IBM-Cloud/terraform-provider-ibm is using Terraform >0.12, and the examples in that repo do not match up with the tutorials in the docs.

**Comment by geemurth** [comment]
Hi Rampad,

Could you please share us the example and the documentation link that you are referring to. Based on that, we will work to fix the issue. 

Thanks,
Geetha

**Comment by geemurth** [comment]
Since, we haven't heard from Rampad, we are closing this ticket. Once we hear from you, will work on this.
