### ISSUE TITLE
Path to terraform.d should have a period to reference hidden folder

### ISSUE THREAD

**Issue by JohnPaulParkin** [ibm-cloud-docs/terraform#68]
On the page https://cloud.ibm.com/docs/terraform?topic=terraform-setup_cli#configure_provider

in Step 2 "Install the IBM Cloud Provider plug-in for Terraform" the folder referred to as `terraform.d` needs to have period in front of the path since this is supposed to be a hidden folder.

The path should be `$HOME/.terraform.d/plugins` 

Without this the plugins are not found since they are not installed in the right location.  The documentation mentions a hidden file, but the copy/paste examples are missing the period.

**Comment by geemurth** [comment]
This is updated in the docs, thanks for catching this, John.
